title: BEEZOO
author: Jack Andrew
email: Jack@beezoo.nyc
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.beezoo.nyc" #
github_username:  bz-ja
site_repository: https://github.com/beezoo/beezoo
show_excerpts: true
excerpt_separator: <!--excerpt-->
header_pages:
  - about.md
  - category/bu.markdown
  - category/fr-distilling.markdown
  - category/halftone-web-graphics.markdown
  - category/lemon-lemon.markdown
  - category/sobe.markdown
  - category/pepsico.markdown
  # - tag/log.markdown

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
